# Generated by Django 4.2.7 on 2026-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('interpreted_text', models.TextField()),
                ('summary', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_version', models.CharField(default='llama-2-7b', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_interpretations',
                'ordering': ['-created_at'],
            },
        ),
    ]
